### ISSUE TITLE
What resin do you use?

### ISSUE THREAD

**Issue by christiangenco** [kenp-io/not-for-airpods-repairs#2]
In your [AirPods' Dirty Secret video](https://www.youtube.com/watch?v=RQqk45ps9kg) you SLA print with a white resin that ends up looking really close to the actual Airpods shiny white plastic.

What's that resin called and where did you buy it?

**Comment by aimerib** [comment]
From the looks on the bottle, it looks like an ANYCUBIC 3D Printer Resin white, which would make sense since the SLA printer is also an anycubic.

Maybe this: https://www.amazon.com/ANYCUBIC-UV-Curing-Precision-Excellent-Fluidity/dp/B07G34K22M/
(Link for picture references. There are probably better places to get this resin from)

**Comment by kenp-io** [comment]
What @aimerib said! Sourcing depends on where you're from. It won't look like the original AirPods case, I had to paint it. Might as well go crazy and embrace a different color :)
